@API_HostAddress = http://localhost:5261

# @name CreateAnalysisSingleImage

POST {{API_HostAddress}}/api/RecipeAnalysis/
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary-for-http-file

--boundary-for-http-file
Content-Disposition: form-data; name="Name"

My First Recipe Analysis
--boundary-for-http-file
Content-Disposition: form-data; name="Images"; filename="pantry.webp"
Content-Type: image/png

<@ pantry.webp
--boundary-for-http-file--

###